name: PyTorch CI-CD
on: [push]

jobs:
  Build-And-Run:
    runs-on: ubuntu-latest
    name: Inline docker run
    container: docker:latest
    steps:
      - name: Build image
        run: docker build -f Dockerfile -t my_image:no_cuda
      - name: Run image
        run: |
          sudo docker run --rm -it --init \
          --ipc=host \
          --volume="$PWD:/app"  \
          my_image:no_cuda python main.py
  Docker-service:
    runs-on: ubuntu-latest
    name: Test docker as github service
    steps:
      - name: Hello world action step
        uses: actions/torch-docker-action@v1
        with:
          python-file: 'main.py'